Repository Graylog2/documentation, pull requests merged in 2019-02, with the labels that each got.

#541 updated guides and versions
  pages/installation/operating_system_packages.rst
  pages/installation/os/centos.rst
  pages/installation/os/debian.rst
  pages/installation/os/sles.rst
  pages/installation/os/ubuntu.rst
Labels: ready-for-review

#547 Fix script alert config option
  pages/configuration/server.conf.rst
Labels: ready-for-review

#549 Increase default content width by 200px
  .gitignore
  _static/theme_overrides.css
  conf.py
Labels: ready-for-review

#553 Content pack fixup
  pages/configuration/server.conf.rst
  pages/getting_started/explore.rst
  pages/marketplace.rst
  pages/sending_data.rst
Labels: content-packs, documentation, ready-for-review

#554 Reporting documentation
  images/reporting-configuration-page.png
  images/reporting-create-page.png
  images/reporting-history-page.png
  images/reporting-reports-page.png
  index.rst
  pages/configuration/server.conf.rst
  pages/faq.rst
  pages/reporting.rst
  pages/reporting/setup.rst
  pages/reporting/usage.rst
Labels: ready-for-review

#556 Update enterprise documentation
  pages/archiving.rst
  pages/archiving/setup.rst
  pages/archiving/usage.rst
  pages/auditlog.rst
  pages/auditlog/setup.rst
  pages/auditlog/usage.rst
  pages/enterprise/setup.rst
Labels: ready-for-review

#555 Add Enterprise Setup tar download link back
  conf.py
  pages/enterprise/setup.rst
  pages/integrations.rst
  pages/integrations/setup.rst
Labels: ready-for-review

#551 Update Sidecar documentation to 1.0
  images/sidecar_conf_variable-fs8.png
  images/sidecar_conf_variable.png
  images/sidecar_conf_variable2-fs8.png
  images/sidecar_conf_variable2.png
  images/sidecar_configuration.png
  images/sidecar_new_collector-fs8.png
  images/sidecar_new_collector.png
  images/sidecar_overview-fs8.png
  images/sidecar_sbs0-fs8.png
  images/sidecar_sbs0.png
  images/sidecar_sbs1-fs8.png
  images/sidecar_sbs1.png
  images/sidecar_sbs2-fs8.png
  images/sidecar_sbs2.png
  images/sidecar_sbs3-fs8.png
  images/sidecar_sbs3.png
  images/sidecar_sbs4-fs8.png
  images/sidecar_sbs4.png
  images/sidecar_sbs5-fs8.png
  images/sidecar_sbs5.png
  images/sidecar_sbs6-fs8.png
  images/sidecar_sbs6.png
  images/sidecar_sbs7-fs8.png
  images/sidecar_sbs7.png
  images/sidecars_overview-fs8.png
  images/sidecars_overview.png
  index.rst
  pages/collector_sidecar.rst
  pages/getting_started/explore.rst
  pages/secure/sec_graylog_beats.rst
  pages/sending_data.rst
  pages/sidecar.rst
Labels: ready-for-review

#544 Add first draft of content pack documentation
  images/content_pack_parameter-fs8.png
  images/content_pack_parameter.png
  images/content_pack_selection-fs8.png
  images/content_pack_selection.png
  images/content_pack_show-fs8.png
  images/content_pack_show.png
  index.rst
  pages/content_packs.rst
Labels: content-packs, documentation, ready-for-review

#559 Add note about collector_binaries_whitelist
  pages/sidecar.rst
Labels: ready-for-review

#563 Add Sidecar upgrade documentation
  images/sidecar_mig_1.png
  images/sidecar_mig_2.png
  images/sidecar_mig_3.png
  images/sidecar_mig_4.png
  images/sidecar_mig_5.png
  pages/sidecar.rst
Labels: documentation, ready-for-review

#564 Ignore vim *.swp files in sphix autobuild
  Makefile
Labels: ready-for-review

#565 Note on Graylog Password Secret (#533)
  pages/installation/docker.rst
Labels: ready-for-review

#566 Update API token creation to new UI
  images/api_tokens_1-fs8.png
  images/api_tokens_2-fs8.png
  images/api_tokens_3-fs8.png
  images/api_tokens_4-fs8.png
  pages/configuration/rest_api.rst
Labels: ready-for-review

#562 Remove legacy content packs
  pages/upgrade/graylog-3.0.rst
Labels: content-packs, documentation, ready-for-review

#567 Fix 2.5 sidecar link
  pages/sidecar.rst
  pages/upgrade/graylog-3.0.rst
Labels: ready-for-review

#568 Use absolute path for 2.5 link
  pages/sidecar.rst
Labels: ready-for-review

#569 Improve wording
  pages/sidecar.rst
Labels: ready-for-review

#570 Reporting documentation improvements
  pages/reporting/setup.rst
  pages/reporting/usage.rst
Labels: ready-for-review

#574 Revert image scale settings
  pages/sidecar.rst
Labels: documentation, ready-for-review

#575 Create links to enlarged images
  pages/sidecar.rst
Labels: documentation, ready-for-review

#576 Mention that /api url changes might affect Sidecars
  pages/upgrade/graylog-3.0.rst
Labels: ready-for-review

#577 Add note about sandboxing on RedHat/CentOS systems
  pages/reporting/setup.rst
Labels: ready-for-review

#571 Update geolocation documentation
  pages/geolocation.rst
  pages/lookuptables.rst
  pages/pipelines/stream_connections.rst
Labels: ready-for-review

#548 added Kubernetes select master automatically
  pages/installation/docker.rst
Labels: ready-for-review

#579 added Kubernetes select master automatically
  pages/installation/docker.rst
Labels: ready-for-review

#558 Increase default content width by 200px (2nd try)
  .gitignore
  _static/theme_overrides.css
  _templates/layout.html
  conf.py
Labels: ready-for-review

#581 added multi lookup example
  pages/pipelines/functions.rst
Labels: ready-for-review

#583 Created sec_adcs_certificates.rst
  pages/secure/sec_adcs_certificates.rst
Labels: ready-for-review

#586 Mention new configuration assignment
  pages/sidecar.rst
Labels: ready-for-review

#588 Typo in plugin directory name
  pages/plugins.rst
Labels: need-input
