Repository Graylog2/documentation, pull requests merged in 2020-03, with the labels that each got.

#823 made clear functions for mongodb lut
  pages/lookuptables.rst
  pages/pipelines/functions.rst
Labels: ready-for-review

#825 Alerting by example
  images/event-details.png
  images/event-email.png
  images/event-filter.png
  images/event-key.png
  images/event-notification.png
  images/event-search.png
  images/event-summary.png
  images/priority.png
  pages/alerting/alerting-by-example.rst
  pages/alerts.rst
  pages/streams.rst
Labels: improvement, ready-for-review

#829 Add page about search parameters
  images/searching/parameter_creation_step1.png
  images/searching/parameter_creation_step2.png
  images/searching/parameter_dashboard_dialog.png
  images/searching/parameter_example.png
  pages/queries.rst
  pages/searching/parameters.rst
Labels: ready-for-review, search

#830 Add changelog for 3.2.3
  pages/changelog.rst
  pages/enterprise/changelog.rst
Labels: ready-for-review

#782 update dependencies
  requirements.txt
Labels: ready-for-review

#838 Add changelog for 3.2.4
  pages/changelog.rst
  pages/enterprise/changelog.rst
Labels: ready-for-review

#824 make enterprise more clear
  pages/alerts.rst
  pages/enterprise/intro.rst
  pages/enterprise/setup.rst
  pages/integrations.rst
Labels: ready-for-review

#843 Rename widget field action "Aggregate" to "Show top values"
  images/searching/views_field_actions.png
  images/searching/views_field_actions_v2.png
  pages/searching/widgets.rst
Labels: ready-for-review

#842 all updates
  requirements.txt
Labels: ready-for-review
