Repository Graylog2/documentation, pull requests merged in 2020-02, with the labels that each got.

#785 Update configuration/server.conf for 3.2
  pages/configuration/server.conf.rst
Labels: ready-for-review

#786 3.2 alerting updates
  index.rst
  pages/alerts.rst
  pages/streams/alerts.rst
  pages/upgrade/graylog-3.2.rst
Labels: ready-for-review

#787 Use python3 per default
  README.md
Labels: ready-for-review

#788 fix integration plugins version mentioned
  pages/integrations/setup.rst
Labels: ready-for-review

#789 update centos install page with yum instead of apt-get
  pages/installation/os/centos.rst
Labels: documentation

#790 Add changelog for 3.2.1
  pages/changelog.rst
  pages/enterprise/changelog.rst
Labels: ready-for-review

#791 Change his to their
  pages/content_packs.rst
Labels: documentation, ready-for-review

#792 Add preliminary documentation for ipfix
  images/ipfix.png
  pages/integrations.rst
  pages/integrations/inputs/ipfix_input.rst
Labels: documentation

#794 Fix links for 3.2 enterprise downloads
  pages/enterprise/setup.rst
Labels: documentation, ready-for-review

#796 Update saved search image paths
  images/searching/saved_search_create_v2.png
  images/searching/saved_search_update_v2.png
  pages/searching/saved_searches.rst
Labels: ready-for-review

#799 Fix typo in ubuntu install
  pages/installation/os/ubuntu.rst
Labels: documentation

#800 Update dashboard page regarding unification of the extended search
  images/dashboard/dashboard_create.png
  images/dashboard/dashboard_create_v2.png
  images/dashboard/dashboard_example.png
  images/dashboard/dashboard_example_v2.png
  images/dashboard/dashboard_export.png
  images/dashboard/dashboard_modify.png
  images/dashboard/dashboard_save.png
  images/dashboard/dashboard_save_dialog.png
  images/dashboard/widget_edit_modal.png
  images/searching/views_widget_aggregation_create.png
  images/searching/views_widget_create.png
  images/searching/widget_aggregation_edit.png
  images/searching/widget_repositioning_and_resizing.png
  pages/dashboards.rst
  pages/queries.rst
  pages/searching/configuration.rst
  pages/searching/csv_export.rst
  pages/searching/decorators.rst
  pages/searching/saved_searches.rst
  pages/searching/widgets.rst
Labels: ready-for-review

#803 clarify on index template
  pages/upgrade/graylog-3.2.rst
Labels: ready-for-review

#798 Add additional information for ipfix input
  images/ipfix_data_types.png
  pages/integrations/inputs/ipfix_input.rst
Labels: documentation

#811 Clarify in FAQ that you cannot replace ES
  pages/faq.rst
Labels: documentation

#816 Add changelog for 3.2.2
  pages/changelog.rst
  pages/enterprise/changelog.rst
Labels: ready-for-review
