Repository Graylog2/documentation, pull requests merged in 2020-11, with the labels that each got.

#979 Replace reference to `quick values` with `aggregate`.
  pages/streams.rst
Labels: ready-for-review

#976 update Slack plugin
  images/alerts_slack_notification.png
  pages/alerts.rst
Labels: documentation, ready-for-review

#980 Replace reference to `quick values` with `aggregate`
  pages/streams.rst
Labels: ready-for-review

#981 Replace reference to `quick values` with `aggregate`
  pages/streams.rst
Labels: ready-for-review

#982 Update decorator usage screen shot.
  images/lookuptables/usage-decorator.png
Labels: ready-for-review

#955 added warn and link
  pages/installation/docker.rst
Labels: ready-for-review

#987 pr feedback
  images/alerts_slack_plugin_notification_1.png
  pages/alerts.rst
Labels: ready-for-review

#990 Update virtual_machine_appliances.rst
  pages/installation/virtual_machine_appliances.rst
Labels: documentation

#1001 Extend upgrading notes for 4.0
  pages/upgrade/graylog-4.0.rst
Labels: ready-for-review

#995 add backlog message items field to Slack Plugin
  images/alerts_slack_notification.png
  images/alerts_slack_plugin_notification.png
  images/alerts_slack_plugin_notification_1.png
  pages/alerts.rst
Labels: documentation, ready-for-review, slack-plugin

#1002 Permission Management
  images/authentication_order_1.png
  images/authentication_order_2.png
  images/create_role_1.png
  images/create_role_2.png
  images/create_user.png
  images/edit_role.png
  images/ldap_group_mapping.png
  images/ldap_settings.png
  images/login_test.png
  images/permissions/permissions_05.png
  images/permissions/permissions_06.png
  images/permissions/permissions_07.png
  images/permissions/permissions_08.png
  images/permissions/permissions_09.png
  images/permissions/permissions_10.png
  images/permissions/permissions_11.png
  images/permissions/permissions_12.png
  images/permissions/permissions_14.png
  images/permissions/permissions_15.png
  images/permissions/permissions_17.png
  images/permissions/permissions_19.png
  images/permissions/permissions_20.png
  images/permissions/permissions_21.png
  images/permissions/permissions_22.png
  images/permissions/permissions_23.png
  images/permissions/permissions_24.png
  images/permissions/permissions_25.png
  images/permissions/permissions_26.png
  images/permissions/permissions_27.png
  images/permissions/permissions_28.png
  images/roles.png
  images/sso_1.png
  images/sysuser.png
  index.rst
  pages/permission_management.rst
  pages/users_and_roles.rst
  pages/users_and_roles/external_auth.rst
  pages/users_and_roles/permission_system.rst
  pages/users_and_roles/roles.rst
  pages/users_and_roles/system_users.rst
  pages/users_and_roles/users.rst
Labels: ready-for-review

#1010 Replace Travis CI with a GitHub Action
  .github/workflows/docs.yml
  .travis.yml
Labels: ready-for-review

#1003 update dependencies
  requirements.txt
Labels: ready-for-review
