Repository Graylog2/documentation, pull requests merged in 2020-10, with the labels that each got.

#950 Cross-reference Elasticsearch upgrade notes.
  pages/upgrade.rst
  pages/upgrade/graylog-4.0.rst
Labels: ready-for-review

#954 added dejavu font
  pages/reporting/setup.rst
Labels: ready-for-review

#956 Add missing 3.3.x changelogs
  pages/changelog.rst
  pages/enterprise/changelog.rst
Labels: ready-for-review

#953 fixed links & added new bugfix release
  conf.py
  pages/enterprise/setup.rst
  pages/integrations/setup.rst
Labels: ready-for-review

#960 Updating documentation for Enterprise Output journal
  pages/integrations/output_framework.rst
Labels: documentation, ready-for-review

#961 Merge Output Journal updates
  pages/integrations/output_framework.rst
Labels: backport, documentation, ready-for-review

#957 added PANOS 9 details
  pages/integrations/inputs/palo_alto_networks_input.rst
Labels: ready-for-review

#958 make windows non that prominent
  pages/faq.rst
  pages/installation.rst
  pages/installation/windows.rst
Labels: ready-for-review

#963 Update ES requirements for 4.0.
  pages/installation.rst
Labels: ready-for-review

#967 Adding notes about auto-sensing ES version.
  pages/configuration/elasticsearch.rst
Labels: ready-for-review

#971 Adding ES rolling upgrade notes.
  pages/upgrade.rst
  pages/upgrade/graylog-4.0.rst
  pages/upgrade/rolling_es_upgrade.rst
Labels: ready-for-review

#974 Initial version of PagerDuty Notification documentation
  images/alerts_pagerduty_notification.png
  pages/alerts.rst
Labels: feature, ready-for-review

#975 Update PagerDuty important box
  pages/alerts.rst
Labels: ready-for-review
