Repository Graylog2/documentation, pull requests merged in 2021-03, with the labels that each got.

#1105 Add missing parenthesis
  pages/configuration/server.conf.rst
Labels: ready-for-review

#1097 Hiding company name in header by using CSS (3.3).
  _static/theme_overrides.css
  conf.py
Labels: improvement, ready-for-review

#1096 Hiding company name in header by using CSS (3.2).
  _static/theme_overrides.css
  conf.py
Labels: improvement, ready-for-review

#1095 Hiding company name in header by using CSS (3.1).
  _static/theme_overrides.css
Labels: improvement, ready-for-review

#1117 Warn users not to run graylog with elastic 7.11
  pages/configuration/elasticsearch.rst
  pages/enterprise/setup.rst
  pages/installation.rst
  pages/installation/operating_system_packages.rst
  pages/upgrade.rst
Labels: documentation
