Repository Graylog2/documentation, pull requests merged in 2021-06, with the labels that each got.

#1152 Add changelog for 4.0.8
  pages/changelog.rst
  pages/enterprise/changelog.rst
Labels: ready-for-review

#1156 Fix typo
  pages/configuration/elasticsearch.rst
Labels: ready-for-review

#1157 Start upgrade notes for 4.1
  pages/upgrade/graylog-4.1.rst
Labels: ready-for-review

#1158 Remove documentation related to virtual machine images
  images/gs/download.png
  images/virtualbox1.png
  images/virtualbox2.png
  images/virtualbox3.png
  pages/architecture.rst
  pages/faq.rst
  pages/getting_started.rst
  pages/getting_started/configure.rst
  pages/getting_started/download_install.rst
  pages/installation.rst
  pages/installation/aws.rst
  pages/installation/virtual_machine_appliances.rst
  pages/secure/securing.rst
  pages/upgrade.rst
Labels: ready-for-review

#1159 Update pages for 4.1
  conf.py
  pages/enterprise/setup.rst
  pages/enterprise/setup/updating.rst
  pages/installation.rst
  pages/installation/docker.rst
  pages/installation/operating_system_packages.rst
  pages/installation/os/centos.rst
  pages/installation/os/debian.rst
  pages/installation/os/sles.rst
  pages/installation/os/ubuntu.rst
Labels: ready-for-review

#1155 Remove extra character
  pages/enterprise/cloud_forwarder.rst
Labels: ready-for-review

#1168 Port fixes from 4.0 branch
  README.md
  pages/enterprise/cloud_forwarder.rst
  pages/installation.rst
  pages/pipelines/functions.rst
  pages/pipelines/rules.rst
  pages/sending/files.rst
Labels: ready-for-review

#1166 Add Prometheus Exporter docs
  images/metrics/node_id_metric.png
  images/metrics/prometheus_metric_names.png
  images/metrics/standard_metrics.png
  index.rst
  pages/metrics.rst
Labels: ready-for-review

#1173 Initial documentation for URLhaus data adapter
  pages/integrations.rst
  pages/integrations/lookups/urlhaus.rst
Labels: documentation, feature, ready-for-review

#1178 Update OS package URLs for the 4.1 release
  pages/enterprise/forwarder/installation.rst
  pages/integrations/lookups/urlhaus.rst
Labels: ready-for-review

#1177 Add changelog for 4.1.0
  pages/changelog.rst
  pages/enterprise/changelog.rst
Labels: ready-for-review

#1179 Fix URLHaus Feed Type indenting
  pages/integrations/lookups/urlhaus.rst
Labels: ready-for-review

#1175 Add greynoise data adapter documentation
  images/integrations/greynoise_config.png
  images/integrations/greynoise_dropdown.png
  images/integrations/greynoise_ent_config.png
  images/integrations/greynoise_ent_result.png
  images/integrations/greynoise_result.png
  pages/integrations.rst
  pages/integrations/greynoise_dataadapter.rst
Labels: documentation
